[project]
name = "kiosk"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.12.10"
dependencies = [
    "altair==4",
    "dotenv>=0.9.9",
    "gpiozero>=2.0.1",
    "pandas==2.3.3",
    "pandas-stubs==3.0.0.260204",
    "pillow>=12.1.1",
    "plotly>=6.6.0",
    "pydeck>=0.9.1",
    "streamlit>=1.55.0",
    "ual>=0.12",
]

[tool.uv.sources]
ual = { git = "https://github.com/urban-air-lab/common" }
