ual_bucket: "ual-hour-inference"
ual_sensor: "ual-3"
lubw_bucket: "lubw-hour"
lubw_sensor: "DEBW015"
start_time: "2025-11-16T00:00:00Z"
stop_time: "2026-01-06T23:00:00Z"
ual3_fields:
  - NO2
lubw_fields:
  - NO2
  - TEMP
  - RLF